version: 2

updates:
  # ===== Python (pip) =====
  - package-ecosystem: "pip"
    directory: "/"                 # pyproject.toml at the repo root
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "direct"  # keep noise low for a library repo
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "deps(pip)"
      include: "scope"
    groups:
      qa-tools:
        patterns:
          - "ruff*"
          - "black*"
          - "pre-commit*"
      testing:
        patterns:
          - "pytest*"
          - "pytest-*"
          - "coverage*"
      imaging:
        patterns:
          - "pillow*"
          - "pikepdf*"

  # ===== GitHub Actions (CI) =====
  - package-ecosystem: "github-actions"
    directory: "/"                 # .github/workflows/*
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:10"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 10
    labels:
      - "ci"
      - "dependencies"
    commit-message:
      prefix: "deps(actions)"
      include: "scope"
    groups:
      runners-and-setup:
        patterns:
          - "actions/checkout"
          - "actions/setup-python"
          - "actions/cache"
      coverage-and-security:
        patterns:
          - "codecov/*"
          - "github/codeql-action*"

# --- Optional safety rails (uncomment if you want to avoid noisy major bumps) ---
#  - package-ecosystem: "pip"
#    directory: "/"
#    ignore:
#      - dependency-name: "pikepdf"
#        update-types: ["version-update:semver-major"]
#      - dependency-name: "pillow"
#        update-types: ["version-update:semver-major"]
