repos:
  # ---- Black: formatteur ----
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        args: ["--line-length", "88"]

  # ---- Flake8: lint ----
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-quotes
        args: ["--max-line-length=88"]

  # (isort désactivé temporairement pour éviter l’échec en CI quand il modifie des fichiers)
