[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "digitalmeve"
description = "DigitalMeve — The Certified Digital Memory (.MEVE)"
readme = "README.md"
requires-python = ">=3.9"
license = {file = "LICENSE"}
authors = [{ name = "BACoul" }]
dynamic = ["version"]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["digitalmeve*"]

[tool.setuptools.dynamic]
version = {attr = "digitalmeve.__version__"}
