[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "digitalmeve"
version = "0.1.1"
description = "DigitalMeve — Certified Digital Memory (.MEVE): generate and verify content-linked proof files"
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }
authors = [
  { name = "DigitalMeve", email = "contact@example.com" }
]
keywords = ["proof", "signature", "verification", "hash", "sha256", "authenticity", "integrity", "meve"]
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Topic :: Security :: Cryptography",
  "Intended Audience :: Developers"
]

# Dépendances runtime
dependencies = [
  "cryptography>=41"
]

[project.urls]
Homepage = "https://github.com/BACOUL/digitalmeve"
Issues = "https://github.com/BACOUL/digitalmeve/issues"

# Scripts CLI (on réutilise tes fichiers existants à la racine)
[project.scripts]
meve-generate = "cli_generate:main"
meve-verify = "cli_verify:main"

[tool.setuptools]
# On utilise la découverte de paquets pour inclure `src` en tant que package
packages = ["src"]
package-dir = {"" = "."}

[tool.setuptools.package-data]
# rien de spécial pour l’instant
src = []
