[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "digitalmeve"
version = "0.1.4"
description = "Outil de génération et vérification de preuves numériques"
authors = [{name = "Ton Nom"}]
dependencies = []
requires-python = ">=3.8"
