name: pre-commit auto-fix

on:
  push:
    branches: [ "main", "master" ]
  pull_request:

permissions:
  contents: write   # nécessaire pour commit des fixes

jobs:
  autofix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install pre-commit
        run: |
          python -m pip install -U pip
          pip install pre-commit

      - name: Run pre-commit on all files (may modify files)
        run: pre-commit run --all-files || true
        # ^ on laisse passer même si un hook "fixe" des fichiers

      - name: Commit fixes (if any)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(pre-commit): auto-fix code style (ruff/black/hooks)"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          push_options: '--force-with-lease'
