name: pre-commit auto-fix

on:
  push:
    branches: [ "main", "master" ]
  pull_request:

permissions:
  contents: write

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"
          cache: "pip"

      - run: |
          python -m pip install -U pip
          pip install pre-commit

      - name: Run pre-commit (may modify files)
        run: pre-commit run --all-files || true

      - name: Commit fixes (if any)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(pre-commit): auto-fix code style (ruff/black/hooks)"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          # ⬇️ N’essaie PAS de committer des fichiers de workflows
          file_pattern: |
            .
            :(exclude).github/workflows/**
