name: publish

on:
  release:
    types: [published]   # seulement quand tu publies une Release
  workflow_dispatch:     # déclenchement manuel si besoin

permissions:
  id-token: write        # Obligatoire pour Trusted Publishing (OIDC)
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: pypi
    if: startsWith(github.ref, 'refs/tags/v')   # sécurité : seulement les tags "v0.1.2" etc.
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build backend
        run: pip install build

      - name: Build wheel/sdist
        run: python -m build

      - name: Publish to PyPI (Trusted Publishing)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
