name: publish

on:
  release:
    types: [published]   # se déclenche quand tu publies une Release GitHub
  workflow_dispatch:     # et aussi à la main depuis l’onglet Actions

permissions:
  contents: read
  id-token: write        # OIDC pour Trusted Publisher (pas de token secret)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build backend
        run: python -m pip install --upgrade pip build

      - name: Build sdist & wheel
        run: python -m build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  publish:
    needs: build
    runs-on: ubuntu-latest

    # IMPORTANT : lier le job à l'environnement 'pypi'
    environment:
      name: pypi
      url: https://pypi.org/project/digitalmeve/

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Publish to PyPI (Trusted Publisher)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages_dir: dist
