name: publish

on:
  release:
    types: [published]   # se déclenche quand tu publies une Release GitHub
  workflow_dispatch:     # permet de lancer à la main depuis l’onglet Actions

permissions:
  contents: read
  id-token: write        # OIDC (Trusted Publishing) — pas de token secret

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/digitalmeve/
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build backend
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build sdist & wheel
        run: python -m build
        # génère dist/*.tar.gz et dist/*.whl

      - name: Publish to PyPI (Trusted Publisher)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
          skip-existing: true
