name: publish
on:
  release:
    types: [published]

jobs:
  build-and-publish:
    environment: pypi
    permissions:
      id-token: write   # OIDC pour PyPI Trusted Publisher
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install build backend
        run: |
          python -m pip install --upgrade pip build
      - name: Build sdist & wheel
        run: python -m build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
