name: publish

on:
  release:
    types: [published]
  # OPTIONNEL : déclenche aussi si on pousse un tag vX.Y.Z (désactive si tu veux Release-only)
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  id-token: write

jobs:
  build-and-publish:
    name: Build & Publish to PyPI (OIDC)
    runs-on: ubuntu-latest

    # évite 2 publish en parallèle sur la même ref
    concurrency:
      group: publish-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade build toolchain
        run: |
          python -m pip install --upgrade pip
          pip install build twine requests

      - name: Sanity check version match
        run: |
          python - << 'PY'
          import tomllib, pathlib, re
          init = pathlib.Path("src/digitalmeve/__init__.py").read_text(encoding="utf-8")
          m = re.search(r'__version__\s*=\s*[\'"]([^\'"]+)[\'"]', init)
          v_py = m.group(1) if m else None
          with open("pyproject.toml","rb") as f:
            v_toml = tomllib.load(f)["project"]["version"]
          assert v_py == v_toml, f"Version mismatch: __init__={v_py} vs pyproject={v_toml}"
          print("Version OK:", v_py)
          PY

      - name: Check if version already on PyPI
        id: pypi_check
        run: |
          python - << 'PY'
          import json, urllib.request, tomllib
          pkg = "digitalmeve"
          with open("pyproject.toml", "rb") as f:
            v_local = tomllib.load(f)["project"]["version"]
          try:
            data = json.loads(urllib.request.urlopen(f"https://pypi.org/pypi/{pkg}/json").read())
            existing = set(data.get("releases", {}).keys())
          except Exception:
            existing = set()
          print("Local version:", v_local)
          skip = "true" if v_local in existing else "false"
          with open("$GITHUB_OUTPUT", "a", encoding="utf-8") as fh:
            fh.write(f"skip_publish={skip}\n")
          PY

      - name: Build sdist & wheel
        if: steps.pypi_check.outputs.skip_publish != 'true'
        run: python -m build

      - name: Twine check artifacts
        if: steps.pypi_check.outputs.skip_publish != 'true'
        run: twine check dist/*

      - name: Publish to PyPI (Trusted Publisher)
        if: steps.pypi_check.outputs.skip_publish != 'true'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          print-hash: true

      # Optionnel : attacher les artefacts à la Release GitHub
      - name: Upload wheels to Release
        if: github.event_name == 'release' && steps.pypi_check.outputs.skip_publish != 'true'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.tar.gz
            dist/*.whl
