name: publish

on:
  release:
    types: [published]

permissions:
  id-token: write   # OIDC pour Trusted Publisher (PyPI)
  contents: read

jobs:
  build-and-publish:
    name: Build & Publish to PyPI
    runs-on: ubuntu-latest
    environment: pypi   # doit correspondre à l’environnement créé dans GitHub (Settings > Environments > pypi)

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build backend
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Sanity check
        run: |
          python -c "import sys; print(sys.version)"
          python -c "import pathlib; print('root:', pathlib.Path('.').resolve())"
          python - <<'PY'
from pathlib import Path
print('pyproject exists:', Path('pyproject.toml').exists())
print('src init exists:', Path('src/__init__.py').exists())
PY

      - name: Build sdist & wheel
        run: python -m build

      - name: Publish to PyPI (Trusted Publisher)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # Pas de token : OIDC via l’environnement "pypi"
          print-hash: true
