name: quality

on:
  push:
  pull_request:

jobs:
  lint:
    name: Ruff & Black (check-only)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install tooling
        run: |
            python -m pip install -U pip
            pip install ruff==0.7.0 black==24.8.0

      - name: Ruff (lint)
        run: ruff check --output-format=github .

      - name: Black (format check)
        run: black --check .
