name: smoke
on:
  workflow_dispatch: {}  # bouton "Run workflow" dans l'onglet Actions
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Show installed package
        run: python -m pip show digitalmeve

      - name: CLI smoke test
        run: |
          meve-generate --help
          meve-verify --help
