name: tests

on:
  push:
  pull_request:

jobs:
  tests:
    name: pytest (${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install project (with dev deps)
        run: |
          python -m pip install -U pip
          # Installe les deps du projet + pytest/pytest-cov si non présents
          pip install -e . "pytest>=7.0" "pytest-cov>=4.0"

      - name: Run tests with coverage
        run: |
          pytest -q --cov=digitalmeve --cov-report=term-missing --cov-report=xml

      - name: Upload coverage.xml artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}
          path: coverage.xml
