name: tests

on:
  push:
    branches: [ "main", "master" ]
  pull_request:

permissions:
  contents: read
  id-token: write   # nécessaire pour Codecov v4 sans token

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Run tests with coverage
        run: pytest -q --cov=digitalmeve --cov-report=xml --cov-report=term-missing

      - name: Enforce coverage threshold
        run: coverage report --fail-under=80

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          fail_ci_if_error: false
          slug: BACOUL/digitalmeve
