name: tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]  # tu peux remettre ["3.9","3.10","3.11"] si tu veux

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
            python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -e .
          pip install pytest

      - name: Sanity check imports
        run: |
          python - << 'PY'
          import importlib
          for m in ["digitalmeve", "digitalmeve.generator", "digitalmeve.utils", "digitalmeve.verifier"]:
              importlib.import_module(m)
          print("imports OK")
          PY

      - name: Run pytest
        run: pytest -q
